### ISSUE TITLE
what is your ast library?why can‘t I use default ast to parse Java source code?

### ISSUE THREAD

**Issue by liulhdarks** [bdqnghi/bi-tbcnn#1]
what is your ast library?why can‘t I use default ast to parse Java source code?

**Comment by bdqnghi** [comment]
you can use what ever AST parser that you want, in our case, we use https://www.srcml.org/

**Comment by bzz** [comment]
Sorry for butting in, but source{d} has also built and maintains an OSS project for containerized parsers infrastructure you might be interested in looking at - project Babelfish https://doc.bblf.sh/ 

It already supports [number of languages](https://doc.bblf.sh/languages.html) and you can see examples of uAST (annotated AST) at http://dashboard.bblf.sh/

Hope this helps!

**Comment by bdqnghi** [comment]
Thanks for the suggestion, i'm also using Babelfish for my next projects, great one :+1:
