### ISSUE TITLE
hello, what is the password for the docker?

### ISSUE THREAD

**Issue by liudonglei** [bdqnghi/bi-tbcnn#2]
I run the ./b commend, but get that error:
[ldl@Z800 bi-tbcnn 20:30:08] $ ./b
Warning: failed to get default registry endpoint from daemon (Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.37/info: dial unix /var/run/docker.sock: connect: permission denied). Using system default: https://index.docker.io/v1/
Password: 

I want to know what is the password for the docker?

**Comment by yijunyu** [comment]
It is no longer required to use the password. Sorry for the late reply.
